"""CONTRACT: `golden/set.json` is the accuracy report's input, so its schema is load-bearing.

The golden set is what OPS-3's published accuracy number is computed from, and what
LP-290 — "zero false passes on warning violations, verified and published" — is verified
against. A typo in a verdict string, a fixture whose expectation names a field that does
not exist, or a checked-in file that has drifted from the catalog it was generated from,
all produce a *number* rather than an error. A wrong number in an accuracy report is worse
than a missing one, because somebody acts on it.

So this file treats the golden set as an external interface and validates it the way the
provider response is validated: every key present, every value in its domain, every
cross-reference resolving.

`test_the_golden_set_covers_at_least_twenty_five_labels` is `xfail(strict=True)` — the
set holds fifteen today and LP-233 asks for twenty-five. The requirement is asserted
rather than described so that reaching it turns the pin red.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

from api.models import Application, Commodity, FieldName, Verdict
from fixtures.generator.catalog import CATALOG, NOT_GENERATED

pytestmark = pytest.mark.contract

ROOT = Path(__file__).resolve().parents[2]
GOLDEN = ROOT / "golden" / "set.json"
LABELS = ROOT / "fixtures" / "labels"

#: LP-233. Every canonical case in the PRD's table, TC-01 through TC-22.
CANONICAL_CASES = [f"TC-{n:02d}" for n in range(1, 23)]

#: LP-233's floor for the synthetic tier.
REQUIRED_LABEL_COUNT = 25


@pytest.fixture(scope="module")
def golden() -> dict[str, Any]:
    if not GOLDEN.exists():  # pragma: no cover - the file is committed
        pytest.fail("golden/set.json is missing; the eval has no input")
    loaded: dict[str, Any] = json.loads(GOLDEN.read_text())
    return loaded


@pytest.fixture(scope="module")
def entries(golden: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = golden["fixtures"]
    return rows


# --------------------------------------------------------------------------------------
# The envelope
# --------------------------------------------------------------------------------------


def test_the_golden_set_declares_its_tier(golden: dict[str, Any]) -> None:
    """Tier A (synthetic) and Tier B (photographs) are never averaged.

    A set generated by our own renderer only proves the pipeline can read our own
    renderer. Blending the two would hide the number that matters, so the file has to
    say which one it is.
    """
    assert golden["tier"] == "A"
    assert "synthetic" in golden["description"].lower()


def test_every_top_level_key_is_one_the_harness_reads(golden: dict[str, Any]) -> None:
    assert set(golden) == {"tier", "description", "fixtures", "not_generated"}


def test_every_entry_carries_the_full_set_of_keys(entries: list[dict[str, Any]]) -> None:
    """A missing key is a `KeyError` mid-eval, or worse a silent default.

    `expect` defaulting to `{}` means "everything should match", which is a real
    expectation and not one you want to acquire by omission.
    """
    required = {
        "name", "commodity", "images", "sha256", "application",
        "expect", "expect_findings", "pending", "notes",
    }
    for entry in entries:
        assert set(entry) == required, entry.get("name")


def test_every_fixture_name_is_unique(entries: list[dict[str, Any]]) -> None:
    names = [entry["name"] for entry in entries]
    assert len(names) == len(set(names))


def test_every_fixture_name_declares_its_canonical_case(
    entries: list[dict[str, Any]],
) -> None:
    """`tc03_title_case_warning` — the case is in the name, so a failure names the row.

    An eval line that reads `fixture_7 failed` sends somebody hunting; one that reads
    `tc03_title_case_warning failed` names the regulation.
    """
    for entry in entries:
        assert re.match(r"^tc\d{2}_[a-z0-9_]+$", entry["name"]), entry["name"]


# --------------------------------------------------------------------------------------
# Every value is in its domain
# --------------------------------------------------------------------------------------


def test_every_commodity_is_a_known_commodity(entries: list[dict[str, Any]]) -> None:
    known = {c.value for c in Commodity}
    for entry in entries:
        assert entry["commodity"] in known, entry["name"]


def test_every_expected_verdict_is_a_real_verdict(entries: list[dict[str, Any]]) -> None:
    """A typo here does not fail — it scores.

    `Verdict("mismatched")` raises inside the harness, but a value that merely never
    matches (`"MISMATCH"`, say) would score every row as wrong and look like an
    accuracy problem rather than a data problem.
    """
    verdicts = {v.value for v in Verdict}
    for entry in entries:
        for field, verdict in entry["expect"].items():
            assert verdict in verdicts, f"{entry['name']}.{field} = {verdict!r}"


def test_every_expectation_names_a_real_field(entries: list[dict[str, Any]]) -> None:
    """An expectation on a field that does not exist is silently never checked.

    `expected_verdicts` looks each row up by field, so a misspelled key simply never
    matches any result — the case appears to pass and tests nothing.
    """
    fields = {f.value for f in FieldName}
    for entry in entries:
        for key in (*entry["expect"], *entry["expect_findings"]):
            assert key in fields, f"{entry['name']}: unknown field {key!r}"


def test_every_expected_finding_code_is_one_the_engine_can_raise(
    entries: list[dict[str, Any]]
) -> None:
    """Codes are cross-referenced against the source, not against a second list here.

    TC-09's verdict is Match and the whole point of the case is the finding riding
    alongside it, so an expectation naming a code that no longer exists would quietly
    stop checking the only thing that case is for.
    """
    emitted = set()
    for module in (ROOT / "api" / "rules").glob("*.py"):
        emitted.update(re.findall(r'code="([a-z0-9_]+)"', module.read_text()))
    for entry in entries:
        for field, codes in entry["expect_findings"].items():
            for code in codes:
                assert code in emitted, f"{entry['name']}.{field}: unknown code {code!r}"


# --------------------------------------------------------------------------------------
# The zero-false-pass gate cannot be annotated away (LP-290, OPS-3)
# --------------------------------------------------------------------------------------
#
# `eval/run.py` computes `is_warning_false_pass` — the one release-blocking metric this
# product has — and two annotations in the catalog can switch it off for a fixture:
#
#   pending="LP-211"   -> `is_warning_false_pass` returns False outright
#   expect={}          -> there is no violation to fail to detect, so the case vanishes
#
# Both are legitimate mechanisms and neither should exist on a government-warning case.
# Setting `expect={}` on tc06 removes it from the gate entirely and the eval still exits
# 0. This file is the layer that bounds the annotations; the harness is the layer that
# reads them, and it is not this branch's file.
#
# These assertions are about the *data*, so they hold whatever `eval/run.py` does with
# the flags next.

#: Canonical cases whose whole purpose is a warning violation. If one of these stops
#: expecting a violation, the case has been turned off rather than fixed.
WARNING_VIOLATION_CASES = {"TC-03", "TC-04", "TC-05", "TC-06", "TC-07"}

#: Verdicts that mean "this field is fine". Mirrors `eval.run._PASSING`, restated rather
#: than imported so that widening it there cannot silently widen the gate here.
_PASSING_VERDICTS = {"match", "not_applicable"}


def _case_of(entry: dict[str, Any]) -> str:
    return f"TC-{entry['name'][2:4]}"


def _pending_exempts_a_warning_from_the_gate() -> bool:
    """Does the harness currently let a `pending` marker suppress a warning false pass?

    Asked of `FieldOutcome` rather than assumed, so this file states the invariant and
    lets either owner satisfy it. The hole needs *both* halves — a harness that honours
    `pending` and a warning fixture that sets it — so closing either one closes it.
    """
    from api.models import FieldName, Verdict
    from eval.run import FieldOutcome

    return not FieldOutcome(
        fixture="probe",
        field=FieldName.GOVERNMENT_WARNING,
        expected=Verdict.MISMATCH,
        actual=Verdict.MATCH,
        pending="LP-000",
    ).is_warning_false_pass


@pytest.mark.xfail(
    strict=True,
    reason=(
        "OPEN: the release-blocking zero-false-pass gate is switched off for TC-06 by "
        "one word. eval.run.FieldOutcome.is_warning_false_pass returns False whenever "
        "`pending` is set, and catalog.py sets pending='LP-211' on tc06_buried_warning "
        "— a government-warning case the tool currently passes. So the metric the "
        "product's central claim (LP-290, OPS-3) is measured by silently excludes one "
        "of the five warning cases, and the eval still reports PASS.\n"
        "The gap it marks is real — prominence heuristics do not exist — but 'the "
        "capability is missing' and 'this case no longer counts against the false-pass "
        "gate' are different statements and only the first is true. The missing "
        "capability is already tracked by a strict xfail in "
        "tests/e2e/test_verify_flows.py, which is the honest place for it.\n"
        "Closing EITHER half clears this: stop honouring `pending` in "
        "is_warning_false_pass (owner: eval/run.py), or drop the marker from the "
        "warning expectation (owner: fixtures/generator/catalog.py)."
    ),
)
def test_no_government_warning_case_is_exempted_from_the_false_pass_gate(
    entries: list[dict[str, Any]]
) -> None:
    """Nothing in the catalog may take a warning case out of the gate."""
    if not _pending_exempts_a_warning_from_the_gate():
        return  # the harness no longer honours the marker; the data cannot bypass it
    offenders = [
        entry["name"]
        for entry in entries
        if entry["pending"] and "government_warning" in entry["expect"]
    ]
    assert offenders == [], (
        f"these fixtures are excluded from the warning false-pass gate: {offenders}"
    )


def test_every_warning_violation_case_still_expects_a_violation(
    entries: list[dict[str, Any]]
) -> None:
    """The second bypass: emptying `expect` makes the case vanish rather than fail.

    With `expect={}` a fixture has no violation to detect, so it cannot produce a false
    pass and drops out of the gate silently — the suite stays green and the exit code
    stays 0. Nothing about the label changed; only the expectation did.

    So the five canonical warning-violation cases are required by name to keep
    expecting a non-passing government-warning verdict. Turning one off now takes an
    edit to this list, which is a conversation rather than a one-word diff.
    """
    by_case = {_case_of(entry): entry for entry in entries}
    for case in sorted(WARNING_VIOLATION_CASES):
        entry = by_case.get(case)
        assert entry is not None, f"{case} has no fixture; the gate has nothing to measure"
        expected = entry["expect"].get("government_warning")
        assert expected is not None, (
            f"{entry['name']} no longer expects a government_warning verdict, so it "
            f"cannot register a false pass"
        )
        assert expected not in _PASSING_VERDICTS, (
            f"{entry['name']} expects {expected!r}, which counts as a pass — the case "
            f"can no longer detect the failure it exists for"
        )


def test_the_warning_false_pass_gate_reads_the_expectations_this_file_bounds() -> None:
    """The two halves are wired together, so bounding the data bounds the gate.

    Without this, the assertions above could be bounding a field the harness had
    stopped consulting — true statements about data nobody reads. Asserted against the
    harness's own outcome object rather than against its source text.
    """
    from api.models import FieldName, Verdict
    from eval.run import FieldOutcome

    violation = FieldOutcome(
        fixture="probe",
        field=FieldName.GOVERNMENT_WARNING,
        expected=Verdict.MISMATCH,
        actual=Verdict.MATCH,
    )
    assert violation.is_warning_false_pass, (
        "a warning expected to mismatch and returning match is not being counted as a "
        "false pass"
    )

    not_a_violation = FieldOutcome(
        fixture="probe",
        field=FieldName.GOVERNMENT_WARNING,
        expected=Verdict.MATCH,
        actual=Verdict.MATCH,
    )
    assert not not_a_violation.is_warning_false_pass


def test_every_pending_marker_names_a_ticket(entries: list[dict[str, Any]]) -> None:
    """"Pending" without a ticket is an expectation nobody owns.

    The pending field keeps a known gap visible without leaving the release gate
    permanently red — which only works if the gap is attached to work somebody will do.
    """
    for entry in entries:
        if entry["pending"]:
            assert re.match(r"^LP-\d{3}$", entry["pending"]), entry["name"]


def test_every_entry_explains_why_it_exists(entries: list[dict[str, Any]]) -> None:
    """Notes are for the human reading the accuracy report, and they earn their place.

    A fixture nobody can explain is a fixture nobody will maintain, and an eval failure
    on one is unactionable.
    """
    for entry in entries:
        assert len(entry["notes"].strip()) > 20, entry["name"]


# --------------------------------------------------------------------------------------
# Cross-references resolve
# --------------------------------------------------------------------------------------


def test_every_application_validates_against_the_domain_model(
    entries: list[dict[str, Any]]
) -> None:
    """The eval feeds these straight into `verify()`.

    An invalid application is an eval *error* rather than a miss, and errors are
    excluded from the accuracy denominator — so a malformed row quietly shrinks the
    set the number is computed over.
    """
    for entry in entries:
        Application.model_validate(entry["application"])


def test_the_application_commodity_agrees_with_the_entry(
    entries: list[dict[str, Any]]
) -> None:
    for entry in entries:
        assert entry["application"]["commodity"] == entry["commodity"], entry["name"]


def test_every_referenced_image_exists_on_disk(entries: list[dict[str, Any]]) -> None:
    """A missing PNG is an eval error, which is excluded from the denominator."""
    for entry in entries:
        assert entry["images"], entry["name"]
        for image in entry["images"]:
            assert (LABELS / image).exists(), f"{entry['name']}: {image} not rendered"


def test_every_image_has_a_recorded_digest(entries: list[dict[str, Any]]) -> None:
    """LP-123: determinism is the requirement, and the digest is how it is checked."""
    for entry in entries:
        assert set(entry["sha256"]) == set(entry["images"]), entry["name"]
        for digest in entry["sha256"].values():
            assert re.fullmatch(r"[0-9a-f]+", digest), entry["name"]


def test_the_checked_in_set_matches_the_catalog_it_was_generated_from(
    entries: list[dict[str, Any]]
) -> None:
    """The file on disk and the code that produces it must not drift.

    `golden/set.json` is committed so a human can read and initial it, and generated
    from `CATALOG` so it cannot be edited into disagreement with the fixtures. Both
    only hold if something checks.
    """
    assert [entry["name"] for entry in entries] == [spec.name for spec in CATALOG]


def test_every_expectation_matches_the_catalog_spec(
    entries: list[dict[str, Any]]
) -> None:
    """Field by field, not just the names.

    Editing an expectation in the JSON without editing the spec would make the eval
    check something the fixture was never built to exercise.
    """
    by_name = {spec.name: spec for spec in CATALOG}
    for entry in entries:
        spec = by_name[entry["name"]]
        assert entry["expect"] == spec.expect, entry["name"]
        assert entry["expect_findings"] == spec.expect_findings, entry["name"]
        assert entry["pending"] == spec.pending, entry["name"]


# --------------------------------------------------------------------------------------
# Coverage of the canonical cases (LP-233)
# --------------------------------------------------------------------------------------


def _covered_cases(entries: list[dict[str, Any]]) -> set[str]:
    generated = {f"TC-{entry['name'][2:4]}" for entry in entries}
    return generated | set(NOT_GENERATED)


def test_every_canonical_case_is_either_generated_or_explained(
    entries: list[dict[str, Any]]
) -> None:
    """All 22 rows of the PRD's table are accounted for.

    Seven cannot be generated from a spec — an angled photograph, glare, a cat — and
    each says so by name in `NOT_GENERATED`. "Accounted for" means generated *or*
    explained; what it must never mean is absent.
    """
    missing = sorted(set(CANONICAL_CASES) - _covered_cases(entries))
    assert missing == [], f"canonical cases with no fixture and no explanation: {missing}"


def test_every_ungenerated_case_says_why(entries: list[dict[str, Any]]) -> None:
    for case, reason in NOT_GENERATED.items():
        assert case in CANONICAL_CASES, case
        assert len(reason.strip()) > 10, case


def test_no_case_is_both_generated_and_listed_as_ungenerated(
    entries: list[dict[str, Any]]
) -> None:
    """Two sources of truth for one case is one too many."""
    generated = {f"TC-{entry['name'][2:4]}" for entry in entries}
    assert generated & set(NOT_GENERATED) == set()


def test_the_warning_cases_are_all_generated(entries: list[dict[str, Any]]) -> None:
    """TC-03 through TC-07 are the warning statement, and they carry LP-290.

    "Zero false passes on warning violations" is verified against these five. A warning
    case that quietly moved into the ungenerated list would remove the evidence for the
    product's central claim.
    """
    generated = {f"TC-{entry['name'][2:4]}" for entry in entries}
    for case in ("TC-03", "TC-04", "TC-05", "TC-06", "TC-07"):
        assert case in generated, f"{case} must be a generated fixture"


@pytest.mark.xfail(
    strict=True,
    reason=(
        "OPEN (LP-233): the golden set holds 15 labels; the ticket asks for at least 25 "
        "spanning every TC row. Accuracy on a 15-fixture set is a number with wide error "
        "bars, and the per-condition breakdown LP-236 wants needs more than one fixture "
        "per condition. Asserted rather than described so that reaching 25 turns this "
        "red. Owner: fixtures/generator/catalog.py."
    ),
)
def test_the_golden_set_covers_at_least_twenty_five_labels(
    entries: list[dict[str, Any]]
) -> None:
    assert len(entries) >= REQUIRED_LABEL_COUNT


@pytest.mark.xfail(
    strict=True,
    reason=(
        "OPEN (LP-235): no entry records who hand-verified its expected verdicts. The "
        "eval's authority rests on somebody having checked each expectation against the "
        "rendered pixels once; without a reviewer's initials and a date in the file, "
        "that claim is unsourced. Fix: add a `reviewed` key (initials + ISO date) to "
        "LabelSpec and emit it into golden/set.json. "
        "Owner: fixtures/generator/spec.py, fixtures/generator/build.py."
    ),
)
def test_every_expected_verdict_has_been_hand_verified(
    entries: list[dict[str, Any]]
) -> None:
    for entry in entries:
        assert entry.get("reviewed"), entry["name"]
