"""The golden set — one spec per canonical test case, with expected verdicts.

Tier A of the two-tier set (BUILD.md §5): synthetic, deterministic, regenerable, and the
tier that gates CI. Tier B is real bottle photographs, reported separately and never
gating, because a set generated by our own renderer only proves the pipeline can read our
own renderer.

Every spec here names the TC it covers. A TC with no spec is a hole in the golden set.
"""

from __future__ import annotations

from api import canon
from fixtures.generator.spec import LabelSpec

#: The compliant baseline every defective variant is built from.
OLD_TOM = LabelSpec(
    name="tc01_old_tom_clean",
    face="single",
    notes="TC-01 clean match. The brief's sample label, fully compliant.",
)


CATALOG: list[LabelSpec] = [
    OLD_TOM,

    OLD_TOM.with_(
        name="tc02_stones_throw",
        brand_name="STONE’S THROW",
        class_type="Kentucky Straight Bourbon Whiskey",
        application_overrides={"brand_name": "Stone's Throw"},
        expect={"brand_name": "acceptable_variation"},
        notes=(
            "TC-02. Label carries a curly apostrophe and all caps; the application says "
            "'Stone's Throw'. Dave's case — obviously the same thing, and the agent must "
            "see the judgment call rather than a silent pass."
        ),
    ),

    OLD_TOM.with_(
        name="tc03_title_case_warning",
        warning_header_case="title",
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-03. Jenny's catch — she rejected a real label for exactly this. The "
            "header reads 'Government Warning:' instead of all caps."
        ),
    ),

    OLD_TOM.with_(
        name="tc04_bold_warning_body",
        warning_body_bold=True,
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-04. 16.22's inverse rule: only 'GOVERNMENT WARNING' may be bold, the "
            "remainder must not be. The one almost everyone misses."
        ),
    ),

    OLD_TOM.with_(
        name="tc05_reworded_warning",
        warning_text=canon.WARNING_BODY.replace(
            "women should not drink alcoholic beverages during pregnancy",
            "pregnant women should not drink alcoholic beverages",
        ),
        expect={"government_warning": "mismatch"},
        notes="TC-05. Paraphrased clause (1). Must produce a word-level diff as evidence.",
    ),

    OLD_TOM.with_(
        name="tc06_buried_warning",
        warning_scale=0.45,
        warning_contrast=0.35,
        expect={"government_warning": "unreadable"},
        expect_findings={
            "government_warning": ["warning_less_prominent", "warning_low_contrast"]
        },
        notes=(
            "TC-06. Warning present and verbatim but shrunk and low-contrast — the "
            "'creative' evasion Jenny described. The wording is right, so this is not a "
            "correction to send back; the PRD asks for Needs review with the region "
            "shown. Unreadable is the verdict that carries that meaning without "
            "claiming the label is wrong (LP-211, LP-212)."
        ),
    ),

    OLD_TOM.with_(
        name="tc03b_non_bold_warning_header",
        warning_header_bold=False,
        expect={"government_warning": "mismatch"},
        expect_findings={"government_warning": ["warning_header_not_bold"]},
        notes=(
            "WARN-2's other half. TC-03 covers capitals; nothing covered bold, so a "
            "checker that ignored the bold signal entirely would have passed the whole "
            "fixture set. Capitals are correct here and only the weight is wrong."
        ),
    ),

    OLD_TOM.with_(
        name="tc06b_warning_contrast_unread",
        warning_signals_unread=frozenset({"contrast_ok", "relative_size"}),
        expect={"government_warning": "unreadable"},
        expect_findings={"government_warning": ["warning_contrast_unverified"]},
        notes=(
            "A compliant label the extractor could not fully judge. The artwork is "
            "clean — verbatim wording, correct capitals, correct weight — and the "
            "reading comes back unable to say whether the statement contrasts with its "
            "background. That combination used to reach Ready to approve, and no "
            "fixture could produce it because the fake derived every signal from the "
            "spec and therefore always answered."
        ),
    ),

    OLD_TOM.with_(
        name="tc03c_warning_bold_unread",
        warning_signals_unread=frozenset({"header_is_bold", "body_is_bold"}),
        expect={"government_warning": "unreadable"},
        expect_findings={
            "government_warning": [
                "warning_header_bold_unverified", "warning_body_bold_unverified"
            ]
        },
        notes=(
            "The abstention the whole tri-state design was built for, finally "
            "reachable from a fixture. Bold is the signal the weakest model is likeliest "
            "to decline on, and the golden set could not express a decline until now."
        ),
    ),

    OLD_TOM.with_(
        name="tc05b_truncated_warning",
        warning_text=canon.WARNING_BODY[: canon.WARNING_BODY.index("(2)")].strip(),
        expect={"government_warning": "mismatch"},
        expect_findings={"government_warning": ["warning_text_truncated"]},
        notes=(
            "LP-210. The commonest partial warning in the wild: clause (1) printed and "
            "clause (2) dropped, usually because the artwork ran out of room. Distinct "
            "from TC-05, which rewords rather than truncates, and the correction the "
            "applicant has to make is a different one."
        ),
    ),

    OLD_TOM.with_(
        name="tc07_missing_warning",
        include_warning=False,
        expect={"government_warning": "missing"},
        notes="TC-07. No warning anywhere. Disqualifying on its own, ranked first.",
    ),

    OLD_TOM.with_(
        name="tc08_abv_mismatch",
        alcohol_text="40% Alc./Vol. (80 Proof)",
        application_overrides={"alcohol_content": 45.0},
        expect={"alcohol_content": "mismatch"},
        notes=(
            "TC-08. Label says 40%, application says 45%. Internally consistent — 80 "
            "proof is correct for 40% — so this isolates the comparison from TC-09."
        ),
    ),

    OLD_TOM.with_(
        name="tc09_proof_inconsistent",
        alcohol_text="40% Alc./Vol. (90 Proof)",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["proof_abv_inconsistent"]},
        notes=(
            "TC-09. 90 proof means 45%, so the label disagrees with itself. The verdict "
            "is Match — the label agrees with the application — and the inconsistency "
            "is a finding. Checking verdicts alone would score this as passing while "
            "the defect went undetected."
        ),
    ),

    OLD_TOM.with_(
        name="tc10_non_standard_fill",
        net_contents="733 mL",
        expect={"net_contents": "match"},
        expect_findings={"net_contents": ["non_standard_fill"]},
        notes=(
            "TC-10. Matches the application exactly AND is a non-authorized size. The "
            "verdict is Match; the compliance failure rides along as a finding. If this "
            "ever reports a mismatch, the two checks have been conflated."
        ),
    ),

    OLD_TOM.with_(
        name="tc16_front_back",
        face="front",
        expect={},
        notes=(
            "TC-16. Two-image application — brand on the front, warning on the back. "
            "Renders as _front.png and _back.png; the warning must be found across "
            "images before Missing is declared."
        ),
    ),

    OLD_TOM.with_(
        name="tc17_table_wine",
        commodity="wine",
        brand_name="RIVERBEND CELLARS",
        class_type="Table Wine",
        alcohol_text="",
        producer="Riverbend Cellars, Napa, California",
        expect={"alcohol_content": "not_applicable"},
        notes=(
            "TC-17. Table wine at or below 14% may omit alcohol content. Must be Not "
            "applicable, never a false Missing."
        ),
    ),

    OLD_TOM.with_(
        name="tc18_malt_no_abv",
        commodity="malt",
        brand_name="IRON GATE BREWING",
        class_type="India Pale Ale",
        alcohol_text="",
        net_contents="355 mL",
        producer="Iron Gate Brewing, Portland, Oregon",
        expect={"alcohol_content": "not_applicable"},
        notes="TC-18. Alcohol content is federally optional on malt. Not applicable.",
    ),

    OLD_TOM.with_(
        name="tc19_import_missing_origin",
        brand_name="MAISON CLAIRE",
        class_type="Cognac",
        producer="Maison Claire, Cognac, France",
        country_of_origin=None,
        application_overrides={"is_import": True, "country_of_origin": "France"},
        expect={"country_of_origin": "missing"},
        notes=(
            "TC-19. Application marks this an import; the label carries no country of "
            "origin. Paired with an application where is_import is true."
        ),
    ),

    OLD_TOM.with_(
        name="tc22_spirits_abv_abbreviation",
        alcohol_text="45% ABV",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["spirits_abv_abbreviation"]},
        notes=(
            "TC-22. Value is correct so the verdict is Match; using 'ABV' on a spirits "
            "label is a format finding riding alongside."
        ),
    ),
]

#: TCs that cannot be produced by this generator and need image degradation or real
#: photographs instead. Listed so the gap is explicit rather than silently absent.
NOT_GENERATED: dict[str, str] = {
    "TC-11": "angled photo — applied by degrade.py to a rendered label",
    "TC-12": "glare over the warning — degrade.py",
    "TC-13": "dim lighting — degrade.py",
    "TC-14": "hopeless blur — degrade.py",
    "TC-15": "not a label — needs a non-label image, sourced not generated",
    "TC-20": "batch of 300 — composed from these fixtures at load time",
    "TC-21": "provider down — no image involved, fake adapter test",
}


def by_name(name: str) -> LabelSpec:
    for spec in CATALOG:
        if spec.name == name:
            return spec
    raise KeyError(f"no fixture named {name!r}")
