"""The golden set — one spec per canonical test case, with expected verdicts.

Tier A of the two-tier set: synthetic, deterministic, regenerable, and the
tier that gates CI. Tier B is real bottle photographs, reported separately and never
gating, because a set generated by our own renderer only proves the pipeline can read our
own renderer.

Every spec here names the TC it covers. A TC with no spec is a hole in the golden set.
"""

from __future__ import annotations

from api import canon
from fixtures.generator.spec import LabelSpec

#: The compliant baseline every defective variant is built from.
OLD_TOM = LabelSpec(
    name="tc01_old_tom_clean",
    face="single",
    notes="TC-01 clean match. The brief's sample label, fully compliant.",
)


CATALOG: list[LabelSpec] = [
    OLD_TOM,

    OLD_TOM.with_(
        name="tc02_stones_throw",
        # The curly apostrophe is the fixture, not a typo — TC-02 turns on the label
        # using U+2019 where the application uses U+0027.
        brand_name="STONE’S THROW",  # noqa: RUF001
        class_type="Kentucky Straight Bourbon Whiskey",
        application_overrides={"brand_name": "Stone's Throw"},
        expect={"brand_name": "acceptable_variation"},
        notes=(
            "TC-02. Label carries a curly apostrophe and all caps; the application says "
            "'Stone's Throw'. Dave's case — obviously the same thing, and the agent must "
            "see the judgment call rather than a silent pass."
        ),
    ),

    OLD_TOM.with_(
        name="tc03_title_case_warning",
        warning_header_case="title",
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-03. Jenny's catch — she rejected a real label for exactly this. The "
            "header reads 'Government Warning:' instead of all caps."
        ),
    ),

    OLD_TOM.with_(
        name="tc04_bold_warning_body",
        warning_body_bold=True,
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-04. 16.22's inverse rule: only 'GOVERNMENT WARNING' may be bold, the "
            "remainder must not be. The one almost everyone misses."
        ),
    ),

    OLD_TOM.with_(
        name="tc05_reworded_warning",
        warning_text=canon.WARNING_BODY.replace(
            "women should not drink alcoholic beverages during pregnancy",
            "pregnant women should not drink alcoholic beverages",
        ),
        expect={"government_warning": "mismatch"},
        notes="TC-05. Paraphrased clause (1). Must produce a word-level diff as evidence.",
    ),

    OLD_TOM.with_(
        name="tc06_buried_warning",
        warning_scale=0.45,
        warning_contrast=0.35,
        expect={"government_warning": "mismatch"},
        pending="LP-211",
        notes=(
            "TC-06. Warning present and verbatim but shrunk and low-contrast — the "
            "'creative' evasion Jenny described. Prominence heuristics (LP-211) target "
            "this. The expectation may move — LP-211 makes it `unreadable` rather than "
            "`mismatch` — but it may not disappear: this fixture is listed in "
            "MUST_DECLARE_WARNING_VIOLATION, and emptying its `expect` fails the run."
        ),
    ),

    OLD_TOM.with_(
        name="tc07_missing_warning",
        include_warning=False,
        expect={"government_warning": "missing"},
        notes="TC-07. No warning anywhere. Disqualifying on its own, ranked first.",
    ),

    OLD_TOM.with_(
        name="tc08_abv_mismatch",
        alcohol_text="40% Alc./Vol. (80 Proof)",
        application_overrides={"alcohol_content": 45.0},
        expect={"alcohol_content": "mismatch"},
        notes=(
            "TC-08. Label says 40%, application says 45%. Internally consistent — 80 "
            "proof is correct for 40% — so this isolates the comparison from TC-09."
        ),
    ),

    OLD_TOM.with_(
        name="tc09_proof_inconsistent",
        alcohol_text="40% Alc./Vol. (90 Proof)",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["proof_abv_inconsistent"]},
        notes=(
            "TC-09. 90 proof means 45%, so the label disagrees with itself. The verdict "
            "is Match — the label agrees with the application — and the inconsistency "
            "is a finding. Checking verdicts alone would score this as passing while "
            "the defect went undetected."
        ),
    ),

    OLD_TOM.with_(
        name="tc10_non_standard_fill",
        net_contents="733 mL",
        expect={"net_contents": "match"},
        expect_findings={"net_contents": ["non_standard_fill"]},
        notes=(
            "TC-10. Matches the application exactly AND is a non-authorized size. The "
            "verdict is Match; the compliance failure rides along as a finding. If this "
            "ever reports a mismatch, the two checks have been conflated."
        ),
    ),

    OLD_TOM.with_(
        name="tc16_front_back",
        face="front",
        expect={},
        notes=(
            "TC-16. Two-image application — brand on the front, warning on the back. "
            "Renders as _front.png and _back.png; the warning must be found across "
            "images before Missing is declared."
        ),
    ),

    OLD_TOM.with_(
        name="tc17_table_wine",
        commodity="wine",
        brand_name="RIVERBEND CELLARS",
        class_type="Table Wine",
        alcohol_text="",
        producer="Riverbend Cellars, Napa, California",
        expect={"alcohol_content": "not_applicable"},
        notes=(
            "TC-17. Table wine at or below 14% may omit alcohol content. Must be Not "
            "applicable, never a false Missing."
        ),
    ),

    OLD_TOM.with_(
        name="tc18_malt_no_abv",
        commodity="malt",
        brand_name="IRON GATE BREWING",
        class_type="India Pale Ale",
        alcohol_text="",
        net_contents="355 mL",
        producer="Iron Gate Brewing, Portland, Oregon",
        expect={"alcohol_content": "not_applicable"},
        notes="TC-18. Alcohol content is federally optional on malt. Not applicable.",
    ),

    OLD_TOM.with_(
        name="tc19_import_missing_origin",
        brand_name="MAISON CLAIRE",
        class_type="Cognac",
        producer="Maison Claire, Cognac, France",
        country_of_origin=None,
        application_overrides={"is_import": True, "country_of_origin": "France"},
        expect={"country_of_origin": "missing"},
        notes=(
            "TC-19. Application marks this an import; the label carries no country of "
            "origin. Paired with an application where is_import is true."
        ),
    ),

    OLD_TOM.with_(
        name="tc22_spirits_abv_abbreviation",
        alcohol_text="45% ABV",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["spirits_abv_abbreviation"]},
        notes=(
            "TC-22. Value is correct so the verdict is Match; using 'ABV' on a spirits "
            "label is a format finding riding alongside."
        ),
    ),
]

#: TCs that cannot be produced by this generator and need image degradation or real
#: photographs instead. Listed so the gap is explicit rather than silently absent.
NOT_GENERATED: dict[str, str] = {
    "TC-11": "angled photo — applied by degrade.py to a rendered label",
    "TC-12": "glare over the warning — degrade.py",
    "TC-13": "dim lighting — degrade.py",
    "TC-14": "hopeless blur — degrade.py",
    "TC-15": "not a label — needs a non-label image, sourced not generated",
    "TC-20": "batch of 300 — composed from these fixtures at load time",
    "TC-21": "provider down — no image involved, fake adapter test",
}


#: Fixtures that MUST be scored as government-warning violations on every full run.
#:
#: The zero-false-pass gate's denominator, pinned in the repository. Without this, marking
#: a fixture `pending` silently drops a check and the report still says "0 false passes",
#: just across a smaller set — the cheapest way there is to clear a red build. Shrinking
#: the gate now means shrinking this list, which is a line in a diff someone has to
#: approve. Growing it is free and encouraged.
#:
#: `tc06_buried_warning` is deliberately absent: it is pending LP-211 and currently
#: produces a live false pass (see the eval report). It joins this list when prominence
#: heuristics land and it stops passing.
REQUIRED_WARNING_VIOLATIONS: frozenset[str] = frozenset(
    {
        "tc03_title_case_warning",
        "tc04_bold_warning_body",
        "tc05_reworded_warning",
        "tc07_missing_warning",
    }
)


#: Fixtures whose `expect` MUST declare a government-warning violation.
#:
#: A superset of REQUIRED_WARNING_VIOLATIONS, and the reason it exists is that hardening
#: `pending` left `expect` — one line above it — doing exactly the same job. Deleting
#: `expect={"government_warning": "mismatch"}` makes the row expect a clean Match, so it
#: stops being a declared violation, disappears from the report entirely, and the run
#: prints "0 false passes across 4 violation row(s)" and exits 0. It is a two-line diff
#: that any author revisiting an expectation might make in good faith.
#:
#: `tc06_buried_warning` IS in this list even though it is absent from
#: REQUIRED_WARNING_VIOLATIONS. That asymmetry is the whole point: the one fixture whose
#: expectation is under active discussion is the one the scoring pin cannot cover, because
#: it is `pending`. This list covers it at the declaration level instead. Its expectation
#: may legitimately change (LP-211 moves it from `mismatch` to `unreadable` — still a
#: violation, still non-passing); what it may not do is quietly become no expectation.
MUST_DECLARE_WARNING_VIOLATION: frozenset[str] = REQUIRED_WARNING_VIOLATIONS | {
    "tc06_buried_warning",
}


# --------------------------------------------------------------------------------------
# What a fixture RENDERS — the defect it embodies, not a declaration about it
# --------------------------------------------------------------------------------------
#
# Three reviews found three doors into the zero-false-pass gate, each one line:
# `pending` suppressed the false pass, `expect` removed the declaration, and then simply
# drawing a *different* defect made the pipeline answer `mismatch` — which satisfied the
# expectation, so nothing fired, while the violation the fixture existed to catch went
# right on being undetected.
#
# The pattern was that every pin protected a DECLARATION ABOUT the fixture. These pin the
# DEFECT ITSELF. A fixture whose whole job is to prove that a buried warning is caught has
# to keep burying the warning, and has to keep doing only that: swapping the prominence
# knobs for a title-case header turns a hard case into an easy one that the rules engine
# already catches, and the swap reads like a routine retarget in a diff.

#: Scale below which the warning counts as rendered too small to be prominent (WARN-5).
PROMINENCE_SCALE_CEILING = 0.6

#: Contrast below which the warning counts as rendered too faint (WARN-5).
PROMINENCE_CONTRAST_CEILING = 0.5


def warning_defects(spec: LabelSpec) -> frozenset[str]:
    """Exactly which 27 CFR 16.21/16.22 defects this spec DRAWS.

    Derived from the render parameters, so it describes pixels rather than intent. A spec
    with no defects returns the empty set.
    """
    if not spec.include_warning:
        return frozenset({"absent"})

    defects: set[str] = set()
    if spec.warning_header_case != "upper":
        defects.add("header_not_all_caps")
    if not spec.warning_header_bold:
        defects.add("header_not_bold")
    if spec.warning_body_bold:
        defects.add("body_bold")
    if spec.warning_text is not None:
        defects.add("text_altered")
    if (
        spec.warning_scale < PROMINENCE_SCALE_CEILING
        or spec.warning_contrast < PROMINENCE_CONTRAST_CEILING
    ):
        defects.add("prominence")
    return frozenset(defects)


#: fixture name -> the EXACT defect set it must render. Equality, not containment.
#:
#: Exact, because both directions are attacks. Removing the pinned defect stops the
#: fixture testing anything; adding another one lets an easy defect stand in for a hard
#: one, and the report still shows a green row. `tc06_buried_warning` is the case that
#: matters most: prominence heuristics do not exist yet (LP-211), so it is the one fixture
#: whose expectation is under discussion, and adding `warning_header_case="title"` to it
#: made the pipeline answer `mismatch`, satisfy the expectation, and exit 0.
WARNING_DEFECT_PINS: dict[str, frozenset[str]] = {
    "tc03_title_case_warning": frozenset({"header_not_all_caps"}),
    "tc04_bold_warning_body": frozenset({"body_bold"}),
    "tc05_reworded_warning": frozenset({"text_altered"}),
    "tc06_buried_warning": frozenset({"prominence"}),
    "tc07_missing_warning": frozenset({"absent"}),
}


def misrendered_warning_fixtures(specs: list[LabelSpec]) -> list[str]:
    """Pinned fixtures that no longer draw exactly the defect they were pinned to draw.

    Reported as `name: drew {...}, pinned {...}` so the diff is legible without opening
    the catalog.
    """
    present = {spec.name: spec for spec in specs}
    wrong = []
    for name in sorted(WARNING_DEFECT_PINS.keys() & present.keys()):
        drew = warning_defects(present[name])
        pinned = WARNING_DEFECT_PINS[name]
        if drew != pinned:
            wrong.append(
                f"{name}: draws {sorted(drew) or 'no defect'}, pinned {sorted(pinned)}"
            )
    return wrong


def declares_warning_violation(spec: LabelSpec) -> bool:
    """Does this spec's `expect` say the warning must NOT pass?"""
    expected = spec.expect.get("government_warning")
    return expected is not None and expected not in ("match", "not_applicable")


def undeclared_warning_violations(specs: list[LabelSpec]) -> list[str]:
    """Fixtures the repository requires to declare a violation, that no longer do.

    Only fixtures actually present in `specs` are checked, so a `--fixture` subset run
    does not report every absent name as a defect.
    """
    present = {spec.name: spec for spec in specs}
    return sorted(
        name
        for name in MUST_DECLARE_WARNING_VIOLATION & present.keys()
        if not declares_warning_violation(present[name])
    )


def by_name(name: str) -> LabelSpec:
    for spec in CATALOG:
        if spec.name == name:
            return spec
    raise KeyError(f"no fixture named {name!r}")
