"""The golden set — one spec per canonical test case, with expected verdicts.

Tier A of the two-tier set: synthetic, deterministic, regenerable, and the
tier that gates CI. Tier B is real bottle photographs, reported separately and never
gating, because a set generated by our own renderer only proves the pipeline can read our
own renderer.

Every spec here names the TC it covers. A TC with no spec is a hole in the golden set.

**Read this before adding a knob to `LabelSpec` or editing a warning fixture.**

This file has been attacked four times, and each time one line in it switched off the
zero-false-pass gate while the report printed a confident number and the whole test suite
stayed green. The pins below are shaped by those four findings, and they are worth
understanding before you work around one:

1. **A marker.** `pending="LP-nnn"` dropped a fixture out of both the numerator and the
   denominator, so a live false pass reported as `0 false passes`.
   Answer: `pending` excuses an inaccurate verdict, never a passing one.
2. **A declared expectation.** `expect={}` made the row expect a clean Match, so it stopped
   being a violation at all — it did not fail the gate, it left it.
   Answer: `MUST_DECLARE_WARNING_VIOLATION`, and the pin outranks `expect`.
3. **A rendered defect.** Adding `warning_header_case="title"` to the prominence fixture
   made the pipeline answer `mismatch` for an unrelated reason, satisfying the
   expectation while the violation under test stayed undetected.
   Answer: `WARNING_DEFECT_PINS`, exact sets in both directions.
4. **A type.** `warning_body_bold=None` drew byte-identical pixels — the renderer reads it
   as falsy — while the extractor reported the tri-state "could not determine", which made
   the verdict non-passing for, again, an unrelated reason.
   Answer: identity tests instead of truthiness, plus `spec_type_problems`.

The pattern: each door was a layer deeper than the last, and each was found by someone
attacking the gate rather than confirming it. Three of the four were invisible to the
whole test suite. If you add a knob here, assume it is door five until you have tried to
open it — and prefer a pin that describes *what the fixture draws* over one that describes
a declaration about it.
"""

from __future__ import annotations

from api import canon
from fixtures.generator.spec import LabelSpec

#: The compliant baseline every defective variant is built from.
OLD_TOM = LabelSpec(
    name="tc01_old_tom_clean",
    face="single",
    notes="TC-01 clean match. The brief's sample label, fully compliant.",
)


CATALOG: list[LabelSpec] = [
    OLD_TOM,

    OLD_TOM.with_(
        name="tc02_stones_throw",
        # The curly apostrophe is the fixture, not a typo — TC-02 turns on the label
        # using U+2019 where the application uses U+0027.
        brand_name="STONE’S THROW",
        class_type="Kentucky Straight Bourbon Whiskey",
        application_overrides={"brand_name": "Stone's Throw"},
        expect={"brand_name": "acceptable_variation"},
        notes=(
            "TC-02. Label carries a curly apostrophe and all caps; the application says "
            "'Stone's Throw'. Dave's case — obviously the same thing, and the agent must "
            "see the judgment call rather than a silent pass."
        ),
    ),

    OLD_TOM.with_(
        name="tc03_title_case_warning",
        warning_header_case="title",
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-03. Jenny's catch — she rejected a real label for exactly this. The "
            "header reads 'Government Warning:' instead of all caps."
        ),
    ),

    OLD_TOM.with_(
        name="tc04_bold_warning_body",
        warning_body_bold=True,
        expect={"government_warning": "mismatch"},
        notes=(
            "TC-04. 16.22's inverse rule: only 'GOVERNMENT WARNING' may be bold, the "
            "remainder must not be. The one almost everyone misses."
        ),
    ),

    OLD_TOM.with_(
        name="tc05_reworded_warning",
        warning_text=canon.WARNING_BODY.replace(
            "women should not drink alcoholic beverages during pregnancy",
            "pregnant women should not drink alcoholic beverages",
        ),
        expect={"government_warning": "mismatch"},
        notes="TC-05. Paraphrased clause (1). Must produce a word-level diff as evidence.",
    ),

    OLD_TOM.with_(
        name="tc06_buried_warning",
        warning_scale=0.45,
        warning_contrast=0.35,
        expect={"government_warning": "unreadable"},
        expect_findings={
            "government_warning": ["warning_less_prominent", "warning_low_contrast"]
        },
        notes=(
            "TC-06. Warning present and verbatim but shrunk and low-contrast — the "
            "'creative' evasion Jenny described. The wording is right, so this is not a "
            "correction to send back; the PRD's TC-06 row asks for Needs review with the "
            "region shown, and Unreadable is the only verdict that drives that without "
            "claiming the label is wrong (LP-211, LP-212). "
            "KNOWN TAXONOMY GAP: the PRD defines Unreadable as 'image quality prevents "
            "verification', and here the warning is read perfectly — `extracted` carries "
            "the full statement. The aggregate now matches the PRD and the field verdict "
            "does not. The six-value taxonomy has no verdict for 'read fine, complies as "
            "far as we can tell, needs a human anyway'; adding a seventh is a product "
            "decision (MATCH-1). Recorded rather than resolved. LP-211 may move this "
            "expectation from `mismatch` to `unreadable`; it cannot make it "
            "disappear, because this fixture is named in "
            "MUST_DECLARE_WARNING_VIOLATION and emptying its `expect` fails the run."
        ),
    ),

    OLD_TOM.with_(
        name="tc03b_non_bold_warning_header",
        warning_header_bold=False,
        expect={"government_warning": "mismatch"},
        expect_findings={"government_warning": ["warning_header_not_bold"]},
        notes=(
            "WARN-2's other half. TC-03 covers capitals; nothing covered bold, so a "
            "checker that ignored the bold signal entirely would have passed the whole "
            "fixture set. Capitals are correct here and only the weight is wrong."
        ),
    ),

    OLD_TOM.with_(
        name="tc06b_warning_contrast_unread",
        warning_signals_unread=frozenset({"contrast_ok", "relative_size"}),
        expect={"government_warning": "unreadable"},
        expect_findings={"government_warning": ["warning_contrast_unverified"]},
        notes=(
            "A compliant label the extractor could not fully judge. The artwork is "
            "clean — verbatim wording, correct capitals, correct weight — and the "
            "reading comes back unable to say whether the statement contrasts with its "
            "background. That combination used to reach Ready to approve, and no "
            "fixture could produce it because the fake derived every signal from the "
            "spec and therefore always answered."
        ),
    ),

    OLD_TOM.with_(
        name="tc03c_warning_bold_unread",
        warning_signals_unread=frozenset({"header_is_bold", "body_is_bold"}),
        expect={"government_warning": "unreadable"},
        expect_findings={
            "government_warning": [
                "warning_header_bold_unverified", "warning_body_bold_unverified"
            ]
        },
        notes=(
            "The abstention the whole tri-state design was built for, finally "
            "reachable from a fixture. Bold is the signal the weakest model is likeliest "
            "to decline on, and the golden set could not express a decline until now."
        ),
    ),

    OLD_TOM.with_(
        name="tc05b_truncated_warning",
        warning_text=canon.WARNING_BODY[: canon.WARNING_BODY.index("(2)")].strip(),
        expect={"government_warning": "mismatch"},
        expect_findings={"government_warning": ["warning_text_truncated"]},
        notes=(
            "LP-210. The commonest partial warning in the wild: clause (1) printed and "
            "clause (2) dropped, usually because the artwork ran out of room. Distinct "
            "from TC-05, which rewords rather than truncates, and the correction the "
            "applicant has to make is a different one."
        ),
    ),

    OLD_TOM.with_(
        name="tc07_missing_warning",
        include_warning=False,
        expect={"government_warning": "missing"},
        notes="TC-07. No warning anywhere. Disqualifying on its own, ranked first.",
    ),

    OLD_TOM.with_(
        name="tc08_abv_mismatch",
        alcohol_text="40% Alc./Vol. (80 Proof)",
        application_overrides={"alcohol_content": 45.0},
        expect={"alcohol_content": "mismatch"},
        notes=(
            "TC-08. Label says 40%, application says 45%. Internally consistent — 80 "
            "proof is correct for 40% — so this isolates the comparison from TC-09."
        ),
    ),

    OLD_TOM.with_(
        name="tc09_proof_inconsistent",
        alcohol_text="40% Alc./Vol. (90 Proof)",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["proof_abv_inconsistent"]},
        notes=(
            "TC-09. 90 proof means 45%, so the label disagrees with itself. The verdict "
            "is Match — the label agrees with the application — and the inconsistency "
            "is a finding. Checking verdicts alone would score this as passing while "
            "the defect went undetected."
        ),
    ),

    OLD_TOM.with_(
        name="tc10_non_standard_fill",
        net_contents="733 mL",
        expect={"net_contents": "match"},
        expect_findings={"net_contents": ["non_standard_fill"]},
        notes=(
            "TC-10. Matches the application exactly AND is a non-authorized size. The "
            "verdict is Match; the compliance failure rides along as a finding. If this "
            "ever reports a mismatch, the two checks have been conflated."
        ),
    ),

    OLD_TOM.with_(
        name="tc16_front_back",
        face="front",
        expect={},
        notes=(
            "TC-16. Two-image application — brand on the front, warning on the back. "
            "Renders as _front.png and _back.png; the warning must be found across "
            "images before Missing is declared."
        ),
    ),

    OLD_TOM.with_(
        name="tc17_table_wine",
        commodity="wine",
        brand_name="RIVERBEND CELLARS",
        class_type="Table Wine",
        alcohol_text="",
        producer="Riverbend Cellars, Napa, California",
        expect={"alcohol_content": "not_applicable"},
        notes=(
            "TC-17. Table wine at or below 14% may omit alcohol content. Must be Not "
            "applicable, never a false Missing."
        ),
    ),

    OLD_TOM.with_(
        name="tc18_malt_no_abv",
        commodity="malt",
        brand_name="IRON GATE BREWING",
        class_type="India Pale Ale",
        alcohol_text="",
        net_contents="355 mL",
        producer="Iron Gate Brewing, Portland, Oregon",
        expect={"alcohol_content": "not_applicable"},
        notes="TC-18. Alcohol content is federally optional on malt. Not applicable.",
    ),

    OLD_TOM.with_(
        name="tc19_import_missing_origin",
        brand_name="MAISON CLAIRE",
        class_type="Cognac",
        producer="Maison Claire, Cognac, France",
        country_of_origin=None,
        application_overrides={"is_import": True, "country_of_origin": "France"},
        expect={"country_of_origin": "missing"},
        notes=(
            "TC-19. Application marks this an import; the label carries no country of "
            "origin. Paired with an application where is_import is true."
        ),
    ),

    OLD_TOM.with_(
        name="tc22_spirits_abv_abbreviation",
        alcohol_text="45% ABV",
        expect={"alcohol_content": "match"},
        expect_findings={"alcohol_content": ["spirits_abv_abbreviation"]},
        notes=(
            "TC-22. Value is correct so the verdict is Match; using 'ABV' on a spirits "
            "label is a format finding riding alongside."
        ),
    ),

    # ----------------------------------------------------------------------------------
    # Cases the real photographs found (LP-233).
    #
    # Each of these was a live false-rejection discovered by a bottle on someone's desk,
    # fixed, and pinned as a unit regression. A unit test proves the rule; a fixture puts
    # the case through the whole pipeline and inside the accuracy gate, which is where a
    # regression would actually be felt.
    # ----------------------------------------------------------------------------------

    OLD_TOM.with_(
        name="tc23_all_caps_warning",
        warning_text=canon.WARNING_BODY.upper(),
        expect={"government_warning": "match"},
        notes=(
            "Found on a shipping Fireball bottle. The whole statement set in capitals is "
            "a printing convention, not a defect: 27 CFR 16.22(a)(2) governs the case of "
            "the HEADING and says nothing about the statement after it. Comparing "
            "case-sensitively returned this label for correction, which is the failure "
            "that stops an agent trusting the tool."
        ),
    ),

    OLD_TOM.with_(
        name="tc24_producer_with_lead_in_phrase",
        producer="Bottled by Old Tom Distillery, Bardstown, Kentucky",
        # The application holds the BARE name. Without this override `spec.application()`
        # derives it from the same string, so the filing carries the lead-in phrase too
        # and the fixture proves nothing — which is what it did on the first run.
        application_overrides={"producer_name": "Old Tom Distillery"},
        expect={"producer": "acceptable_variation"},
        notes=(
            "Found on a Found North bottle. Labels print the producer inside a phrase — "
            "'BOTTLED BY', 'PRODUCED AND BOTTLED BY' — while the application holds the "
            "bare name. Called a Mismatch before `contains_after_normalization` existed. "
            "Acceptable variation rather than Match: the difference is real and named."
        ),
    ),

    OLD_TOM.with_(
        name="tc25_country_stated_as_a_phrase",
        commodity="spirits",
        brand_name="NORTHERN REACH",
        country_of_origin="Distilled in Canada",
        application_overrides={"is_import": True, "country_of_origin": "Canada"},
        expect={"country_of_origin": "acceptable_variation"},
        notes=(
            "The same shape as tc24 on a different field, and the second half of the "
            "Found North defect. The positive counterpart to TC-19, which is the case "
            "where origin is genuinely absent."
        ),
    ),

    # ----------------------------------------------------------------------------------
    # Regulatory ground the set did not reach
    # ----------------------------------------------------------------------------------

    OLD_TOM.with_(
        name="tc26_wine_above_fourteen_needs_abv",
        commodity="wine",
        brand_name="STONEHILL VINEYARD",
        class_type="Cabernet Sauvignon",
        alcohol_text="",
        producer="Stonehill Vineyard, Paso Robles, California",
        application_overrides={"alcohol_content": 15.5},
        expect={"alcohol_content": "missing"},
        notes=(
            "The complement to TC-17. Below 14% a table wine may omit alcohol content; "
            "above it the statement is required, so an absent one is Missing rather than "
            "Not applicable. Without this fixture the exemption had no upper edge and a "
            "rule that always answered Not applicable would have scored perfectly."
        ),
    ),

    OLD_TOM.with_(
        name="tc27_malt_in_fluid_ounces",
        commodity="malt",
        brand_name="IRON GATE BREWING",
        class_type="India Pale Ale",
        alcohol_text="",
        net_contents="12 fl oz",
        producer="Iron Gate Brewing, Asheville, North Carolina",
        expect={"alcohol_content": "not_applicable"},
        notes=(
            "Every other fixture states net contents in millilitres. US malt beverages "
            "are labelled in fluid ounces, so the standards-of-fill path had never been "
            "exercised against the unit an agent actually sees most often."
        ),
    ),

    OLD_TOM.with_(
        name="tc28_brand_with_an_accent",
        brand_name="CÔTE SAUVAGE",
        commodity="wine",
        class_type="Rosé",
        alcohol_text="12.5% Alc./Vol.",
        producer="Côte Sauvage, Willamette Valley, Oregon",
        application_overrides={"brand_name": "Cote Sauvage", "class_type": "Rose"},
        expect={
            "brand_name": "acceptable_variation",
            "class_type": "acceptable_variation",
        },
        notes=(
            "A Courtyard Winery photograph scored 'Dry Rosé' against 'Dry Rose' this way "
            "and it is the right answer, which is why the fixture expects it. The engine "
            "names the difference — 'differences in case, diacritics only; same text' — "
            "rather than folding it into a silent Match. An accent is usually a "
            "transcription artefact, but 'usually' is the agent's call to make, and a "
            "tool that quietly equates two spellings of a brand has decided it for them."
        ),
    ),
]

#: TCs that cannot be produced by this generator and need image degradation or real
#: photographs instead. Listed so the gap is explicit rather than silently absent.
NOT_GENERATED: dict[str, str] = {
    "TC-11": "angled photo — applied by degrade.py to a rendered label",
    "TC-12": "glare over the warning — degrade.py",
    "TC-13": "dim lighting — degrade.py",
    "TC-14": "hopeless blur — degrade.py",
    "TC-15": "not a label — needs a non-label image, sourced not generated",
    "TC-20": "batch of 300 — composed from these fixtures at load time",
    "TC-21": "provider down — no image involved, fake adapter test",
}


#: Fixtures that MUST be scored as government-warning violations on every full run.
#:
#: The zero-false-pass gate's denominator, pinned in the repository. Without this, marking
#: a fixture `pending` silently drops a check and the report still says "0 false passes",
#: just across a smaller set — the cheapest way there is to clear a red build. Shrinking
#: the gate now means shrinking this list, which is a line in a diff someone has to
#: approve. Growing it is free and encouraged.
#:
#: `tc06_buried_warning` is deliberately absent: it is pending LP-211 and currently
#: produces a live false pass (see the eval report). It joins this list when prominence
#: heuristics land and it stops passing.
REQUIRED_WARNING_VIOLATIONS: frozenset[str] = frozenset(
    {
        "tc03_title_case_warning",
        "tc04_bold_warning_body",
        "tc05_reworded_warning",
        "tc07_missing_warning",
    }
)


#: Fixtures whose `expect` MUST declare a government-warning violation.
#:
#: A superset of REQUIRED_WARNING_VIOLATIONS, and the reason it exists is that hardening
#: `pending` left `expect` — one line above it — doing exactly the same job. Deleting
#: `expect={"government_warning": "mismatch"}` makes the row expect a clean Match, so it
#: stops being a declared violation, disappears from the report entirely, and the run
#: prints "0 false passes across 4 violation row(s)" and exits 0. It is a two-line diff
#: that any author revisiting an expectation might make in good faith.
#:
#: `tc06_buried_warning` IS in this list even though it is absent from
#: REQUIRED_WARNING_VIOLATIONS. That asymmetry is the whole point: the one fixture whose
#: expectation is under active discussion is the one the scoring pin cannot cover, because
#: it is `pending`. This list covers it at the declaration level instead. Its expectation
#: may legitimately change (LP-211 moves it from `mismatch` to `unreadable` — still a
#: violation, still non-passing); what it may not do is quietly become no expectation.
MUST_DECLARE_WARNING_VIOLATION: frozenset[str] = REQUIRED_WARNING_VIOLATIONS | {
    "tc06_buried_warning",
}


# --------------------------------------------------------------------------------------
# What a fixture RENDERS — the defect it embodies, not a declaration about it
# --------------------------------------------------------------------------------------
#
# Three reviews found three doors into the zero-false-pass gate, each one line:
# `pending` suppressed the false pass, `expect` removed the declaration, and then simply
# drawing a *different* defect made the pipeline answer `mismatch` — which satisfied the
# expectation, so nothing fired, while the violation the fixture existed to catch went
# right on being undetected.
#
# The pattern was that every pin protected a DECLARATION ABOUT the fixture. These pin the
# DEFECT ITSELF. A fixture whose whole job is to prove that a buried warning is caught has
# to keep burying the warning, and has to keep doing only that: swapping the prominence
# knobs for a title-case header turns a hard case into an easy one that the rules engine
# already catches, and the swap reads like a routine retarget in a diff.

#: Scale below which the warning counts as rendered too small to be prominent (WARN-5).
PROMINENCE_SCALE_CEILING = 0.6

#: Contrast below which the warning counts as rendered too faint (WARN-5).
PROMINENCE_CONTRAST_CEILING = 0.5


#: Rendering knobs that must be a real `bool`. They are typed `bool` on `LabelSpec`, but
#: `with_` funnels through `**changes: object`, so nothing stops `None` being set — and
#: `None` is a tri-state on the *other* side of this boundary, where it means "the
#: extractor could not tell". That mismatch was door four; see the module docstring.
BOOL_RENDER_KNOBS: tuple[str, ...] = (
    "include_warning",
    "warning_header_bold",
    "warning_body_bold",
)

#: Rendering knobs that must be a real number.
NUMERIC_RENDER_KNOBS: tuple[str, ...] = ("warning_scale", "warning_contrast")


def spec_type_problems(spec: LabelSpec) -> list[str]:
    """Rendering knobs holding something the renderer cannot mean."""
    problems = []
    for knob in BOOL_RENDER_KNOBS:
        value = getattr(spec, knob)
        if not isinstance(value, bool):
            problems.append(
                f"{spec.name}: {knob}={value!r} is not a bool. This knob describes what is "
                f"DRAWN, where there is no 'unknown' — the renderer treats None as False "
                f"and draws a clean label, while the extractor reports a tri-state "
                f"'could not determine'. Those are different claims."
            )
    for knob in NUMERIC_RENDER_KNOBS:
        value = getattr(spec, knob)
        if isinstance(value, bool) or not isinstance(value, int | float):
            problems.append(f"{spec.name}: {knob}={value!r} is not a number")
    return problems


def warning_defects(spec: LabelSpec) -> frozenset[str]:
    """Exactly which 27 CFR 16.21/16.22 defects this spec DRAWS.

    Derived from the render parameters, so it describes pixels rather than intent. A spec
    with no defects returns the empty set.

    **Every bool test here is identity, never truthiness.** A truthiness test on a knob
    that is a tri-state one layer down is precisely how door four opened: `if
    spec.warning_body_bold:` read `None` as "no defect", the pin stayed satisfied, and the
    fixture kept drawing byte-identical pixels while the extractor started reporting
    "could not determine" — which made the verdict non-passing for an unrelated reason and
    took the run from exit 3 to exit 0. `is not False` says what is meant: the pin needs
    this body to be *definitely* not bold, and `None` is not definitely anything.
    """
    if spec.include_warning is not True:
        return frozenset({"absent"})

    defects: set[str] = set()
    if spec.warning_header_case != "upper":
        defects.add("header_not_all_caps")
    if spec.warning_header_bold is not True:
        defects.add("header_not_bold")
    if spec.warning_body_bold is not False:
        defects.add("body_bold")
    if spec.warning_text is not None:
        defects.add("text_altered")
    if (
        spec.warning_scale < PROMINENCE_SCALE_CEILING
        or spec.warning_contrast < PROMINENCE_CONTRAST_CEILING
    ):
        defects.add("prominence")
    return frozenset(defects)


#: fixture name -> the EXACT defect set it must render. Equality, not containment.
#:
#: Exact, because both directions are attacks. Removing the pinned defect stops the
#: fixture testing anything; adding another one lets an easy defect stand in for a hard
#: one, and the report still shows a green row. `tc06_buried_warning` is the case that
#: matters most: prominence heuristics do not exist yet (LP-211), so it is the one fixture
#: whose expectation is under discussion, and adding `warning_header_case="title"` to it
#: made the pipeline answer `mismatch`, satisfy the expectation, and exit 0.
WARNING_DEFECT_PINS: dict[str, frozenset[str]] = {
    "tc03_title_case_warning": frozenset({"header_not_all_caps"}),
    "tc04_bold_warning_body": frozenset({"body_bold"}),
    "tc05_reworded_warning": frozenset({"text_altered"}),
    "tc06_buried_warning": frozenset({"prominence"}),
    "tc07_missing_warning": frozenset({"absent"}),
}


def misrendered_warning_fixtures(specs: list[LabelSpec]) -> list[str]:
    """Pinned fixtures that no longer draw exactly the defect they were pinned to draw.

    Reported as `name: drew {...}, pinned {...}` so the diff is legible without opening
    the catalog. A knob holding a value the renderer cannot mean is reported here too:
    the fixture is not drawing what it claims either way, and one gate is easier to trust
    than two.
    """
    present = {spec.name: spec for spec in specs}
    wrong = []
    for spec in specs:
        wrong.extend(spec_type_problems(spec))
    for name in sorted(WARNING_DEFECT_PINS.keys() & present.keys()):
        drew = warning_defects(present[name])
        pinned = WARNING_DEFECT_PINS[name]
        if drew != pinned:
            wrong.append(
                f"{name}: draws {sorted(drew) or 'no defect'}, pinned {sorted(pinned)}"
            )
    return wrong


def declares_warning_violation(spec: LabelSpec) -> bool:
    """Does this spec's `expect` say the warning must NOT pass?"""
    expected = spec.expect.get("government_warning")
    return expected is not None and expected not in ("match", "not_applicable")


def undeclared_warning_violations(specs: list[LabelSpec]) -> list[str]:
    """Fixtures the repository requires to declare a violation, that no longer do.

    Only fixtures actually present in `specs` are checked, so a `--fixture` subset run
    does not report every absent name as a defect.
    """
    present = {spec.name: spec for spec in specs}
    return sorted(
        name
        for name in MUST_DECLARE_WARNING_VIOLATION & present.keys()
        if not declares_warning_violation(present[name])
    )


def by_name(name: str) -> LabelSpec:
    for spec in CATALOG:
        if spec.name == name:
            return spec
    raise KeyError(f"no fixture named {name!r}")
