"""`GET /sample` — the one-click demo (LP-088, LP-308, UX-1).

A reviewer who has to type nine fields before seeing anything has already formed an
opinion about the product, and the opinion is that it makes you do data entry — which is
the exact drudgery this tool exists to remove. That is not a small irony. In production
the application arrives pre-filled from the COLA filing and the agent confirms it; the
form on the setup screen stands in for a record that already exists. So the demo must
open with the realistic flow, not with the seam.

**Several samples rather than one.** A single clean pass shows one of six verdicts and
one of three recommendations. Four samples show a reviewer the whole taxonomy in four
clicks: a clean approval, a value that disagrees, Jenny's title-case catch, and a warning
that is simply not on the label.

**Built from `golden/set.json`, never restated here.** Each entry names a fixture and the
loader reads that fixture's application and images out of the golden set. A sample that
drifted from the set it claims to come from would be a demo of something this project
does not test, and the set is regenerated by `python -m fixtures.generator.build`.
Anything servable is allowlisted from what the manifest actually declares — the path is
never assembled from what a caller sent.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Final

from fastapi import APIRouter
from fastapi.responses import FileResponse

from api import errors

router = APIRouter()

_ROOT = Path(__file__).resolve().parents[2]
_GOLDEN = _ROOT / "golden" / "set.json"
_LABELS = _ROOT / "fixtures" / "labels"

#: Roles by position, for a two-image fixture. The warning lives on the back, which is
#: what makes a pair worth demoing over a single face (TC-16).
_PAIR_ROLES: Final[tuple[str, ...]] = ("front", "back")


@dataclass(frozen=True)
class SampleCase:
    """One demo, described by what a reviewer will SEE rather than by its fixture name."""

    slug: str
    fixture: str
    title: str
    summary: str


#: Ordered so the first click is a pass. A reviewer who opens on a rejection learns what
#: the tool refuses before learning what it does.
CASES: Final[tuple[SampleCase, ...]] = (
    SampleCase(
        slug="clean",
        fixture="tc16_front_back",
        title="A label that checks out",
        summary=(
            "Front and back. Everything matches. Ready to approve."
        ),
    ),
    SampleCase(
        slug="abv-mismatch",
        fixture="tc08_abv_mismatch",
        title="The alcohol content disagrees",
        # NOT "Return for correction", which is what this card claimed until it was run
        # against production. The ABV row is a flat Mismatch, but the warning on the same
        # artwork comes back disputed on prominence, and an unsettled warning outranks a
        # settled mismatch — so the tool asks for eyes rather than issuing a rejection it
        # cannot fully stand behind. A demo card that names the wrong outcome teaches a
        # reviewer to distrust the ones that are right.
        summary=(
            "The application says 45%. The label says 40%. The warning on this label is "
            "also unclear, so you get asked to look rather than a decision."
        ),
    ),
    SampleCase(
        slug="title-case-warning",
        fixture="tc03_title_case_warning",
        title="The warning heading is not in capitals",
        # This card used to promise the catch outright. What actually happens is better
        # and needs saying: the transcription comes back in capitals (models normalise
        # case) while the typography channel reports lowercase. The two disagree, so the
        # tool refuses to settle it and names the regulation instead of guessing. That is
        # the design working — but a card promising a catch, above a row that says "could
        # not be read", reads as the tool missing it.
        summary=(
            "“Government Warning:” is in title case, not capitals. The tool read the "
            "heading two ways and they disagree, so it will not call it either way."
        ),
    ),
    SampleCase(
        slug="missing-warning",
        fixture="tc07_missing_warning",
        title="No government warning at all",
        summary="No warning on either side. The most serious problem a label can have.",
    ),
)

_BY_SLUG: Final[dict[str, SampleCase]] = {case.slug: case for case in CASES}


@lru_cache(maxsize=1)
def _golden() -> dict[str, dict[str, Any]]:
    if not _GOLDEN.exists():
        raise errors.InternalError(
            "The sample set is missing from this build, so the demo cannot load. "
            "Enter an application by hand, or ask whoever runs this service."
        )
    body = json.loads(_GOLDEN.read_text())
    return {entry["name"]: entry for entry in body.get("fixtures", [])}


def _entry(case: SampleCase) -> dict[str, Any]:
    entry = _golden().get(case.fixture)
    if entry is None:
        raise errors.InternalError(
            f"The sample “{case.title}” names a fixture that is not in the "
            f"committed set, so the demo cannot load it. Upload a label of your own."
        )
    return entry


def servable_images() -> frozenset[str]:
    """Every filename the demo may serve, taken from what the samples actually declare."""
    names: set[str] = set()
    for case in CASES:
        names.update(_golden().get(case.fixture, {}).get("images", []))
    return frozenset(names)


def _images_for(case: SampleCase) -> list[dict[str, Any]]:
    files: list[str] = list(_entry(case).get("images", []))
    missing = [name for name in files if not (_LABELS / name).exists()]
    if missing or not files:
        raise errors.InternalError(
            "The sample label images are missing from this build, so the demo cannot "
            "load. Upload a label of your own to try the tool."
        )
    return [
        {
            "index": index,
            # A single-face fixture is "single", not "front": claiming a front when the
            # warning may be on an unphotographed back is the shape of a false Missing.
            "role": _PAIR_ROLES[index] if len(files) > 1 else "single",
            "filename": name,
            "media_type": "image/png",
            "url": f"/sample/images/{name}",
        }
        for index, name in enumerate(files)
    ]


def _payload(case: SampleCase) -> dict[str, Any]:
    entry = _entry(case)
    return {
        "slug": case.slug,
        "title": case.title,
        "summary": case.summary,
        "application": entry["application"],
        "note": entry.get("notes") or None,
        "images": _images_for(case),
    }


@router.get("/sample")
def sample(case: str = "") -> dict[str, Any]:
    """One sample, ready to submit to `/verify`, plus the list of the others.

    `case` is optional and defaults to the first — so a client that knows nothing about
    samples still gets a working demo from a bare `GET /sample`, which is what the
    original single-sample version promised and what `scripts/smoke.sh` checks.
    """
    chosen = _BY_SLUG.get(case) if case else CASES[0]
    if chosen is None:
        raise errors.UserError(
            "That sample does not exist. Choose one of the samples offered on the page.",
            next_step="reload",
            code="unknown_sample",
        )

    body = _payload(chosen)
    body["cases"] = [
        {"slug": c.slug, "title": c.title, "summary": c.summary} for c in CASES
    ]
    return body


@router.get("/sample/images/{name}")
def sample_image(name: str) -> FileResponse:
    """Serve one demo image. Allowlisted by name — never a path built from input."""
    if name not in servable_images():
        raise errors.UserError(
            "That sample image does not exist. Load the sample again from the start.",
            next_step="reload",
            code="unknown_sample_image",
        )
    path = _LABELS / name
    if not path.exists():
        raise errors.InternalError(
            "That sample image is missing from this build. Upload a label of your own "
            "to try the tool."
        )
    return FileResponse(path, media_type="image/png")
